apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs
  labels:
    app: logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      - name: logs
        image: chentex/random-logger
        ports:
        - containerPort: 8080
